- pom.xml
- src/main/java/cl/td/g2/eventos/dto/EventoDTO.java
- src/main/java/cl/td/g2/eventos/mapper/EventMapper.java
- src/main/java/cl/td/g2/eventos/mapper/EventoMapper.java
- src/main/java/cl/td/g2/eventos/model/Evento.java
Implementación de mappers usando MapStruct para convertir entre entidades y DTOs
> Implementación de mappers usando MapStruct para convertir entre entidades y DTOs

- src/main/java/cl/td/g2/eventos/mapper/CategoriaMapper.java
- src/main/java/cl/td/g2/eventos/mapper/CiudadMapper.java
- src/main/java/cl/td/g2/eventos/mapper/EventoMapper.java
Implementación de mappers para entidades Ciudad, Categoria y DTOs usando MapStruct
> Implementación de mappers para entidades Ciudad, Categoria y DTOs usando MapStruct

- src/main/java/cl/td/g2/eventos/mapper/InscripcionMapper.java
- src/main/java/cl/td/g2/eventos/mapper/UsuarioMapper.java
Implementación de mappers para Inscripcion y Usuario usando MapStruct
> Implementación de mappers para Inscripcion y Usuario usando MapStruct

- src/main/java/cl/td/g2/eventos/repository/CategoriaRepository.java
- src/main/java/cl/td/g2/eventos/repository/CiudadRepository.java
- src/main/java/cl/td/g2/eventos/repository/EventoRepository.java
- src/main/java/cl/td/g2/eventos/repository/InscripcionRepository.java
- src/main/java/cl/td/g2/eventos/repository/UsuarioRepository.java
Implementación de repositorios para entidades del proyecto con métodos personalizados
> Implementación de repositorios para entidades del proyecto con métodos personalizados

- src/main/java/cl/td/g2/eventos/mapper/CategoriaMapper.java
- src/main/java/cl/td/g2/eventos/mapper/CiudadMapper.java
- src/main/java/cl/td/g2/eventos/mapper/EventoMapper.java
- src/main/java/cl/td/g2/eventos/mapper/InscripcionMapper.java
- src/main/java/cl/td/g2/eventos/mapper/UsuarioMapper.java
- src/main/java/cl/td/g2/eventos/service/CategoriaService.java
- src/main/java/cl/td/g2/eventos/service/CiudadService.java
- src/main/java/cl/td/g2/eventos/service/EventoService.java
- src/main/java/cl/td/g2/eventos/service/InscripcionService.java
- src/main/java/cl/td/g2/eventos/service/UsuarioService.java
Implementación de servicios (Capa) y modificaciones para los mappers (Conversion LIST)
> Implementación de servicios (Capa) y modificaciones para los mappers (Conversion LIST)

- src/main/java/cl/td/g2/eventos/controller/CategoriaController.java
- src/main/java/cl/td/g2/eventos/controller/CiudadController.java
- src/main/java/cl/td/g2/eventos/controller/EventoController.java
- src/main/java/cl/td/g2/eventos/controller/InscripcionController.java
- src/main/java/cl/td/g2/eventos/controller/UsuarioController.java
Implementación Controladores para todas las entidades
> Implementación Controladores para todas las entidades

- pom.xml
- src/main/java/cl/td/g2/eventos/G2GestionEventosApplication.java
- src/main/java/cl/td/g2/eventos/config/SecurityConfig.java
- src/main/java/cl/td/g2/eventos/config/SwaggerConfig.java
- src/main/java/cl/td/g2/eventos/controller/CategoriaController.java
- src/main/java/cl/td/g2/eventos/controller/CiudadController.java
- src/main/java/cl/td/g2/eventos/controller/EventoController.java
- src/main/java/cl/td/g2/eventos/controller/InscripcionController.java
- src/main/java/cl/td/g2/eventos/controller/UsuarioController.java
- src/main/java/cl/td/g2/eventos/service/UsuarioService.java
- src/main/java/cl/td/g2/eventos/utils/CustomUtil.java
- src/main/resources/application.properties
> llevar cambios de Develop

- pom.xml
- src/test/java/cl/td/g2/eventos/CategoriaControllerTest.java
- src/test/java/cl/td/g2/eventos/CiudadControllerTest.java
- src/test/java/cl/td/g2/eventos/EventoControllerTest.java
- src/test/java/cl/td/g2/eventos/InscripcionControllerTest.java
- src/test/java/cl/td/g2/eventos/UsuarioControllerTest.java
Creacion pruebas unitarias para los Controllers
> Creacion pruebas unitarias para los Controllers

- src/main/java/cl/td/g2/eventos/controller/views/FormInscripcionController.java
- src/main/resources/templates/inscription/form.html
Generar Guardado de la Inscripcion
> Generar Guardado de la Inscripcion

- src/main/java/cl/td/g2/eventos/controller/views/FormCategoriaController.java
- src/main/resources/templates/category/form.html
Generar Guardado de la Categoria
> Generar Guardado de la Categoria

- src/main/java/cl/td/g2/eventos/controller/views/FormUsuarioController.java
- src/main/resources/templates/user/form.html
Generar el guardado del usuario
> Generar el guardado del usuario

- src/main/java/cl/td/g2/eventos/controller/views/FormCiudadController.java
- src/main/resources/templates/city/form.html
Generar el guardado de la ciudad
> Generar el guardado de la ciudad

- src/main/resources/templates/event/form.html
Mejora visual en el orden del formulario Evento
> Mejora visual en el orden del formulario Evento

- src/main/java/cl/td/g2/eventos/controller/calendar/CalendarController.java
- src/main/resources/templates/calendario/view.html
Creacion del Calendario Eventos
> Creacion del Calendario Eventos

- src/main/java/cl/td/g2/eventos/controller/views/FormCategoriaController.java
- src/main/resources/templates/category/edit.html
feat: Añadir formulario y Controller de eliminacion para la entidad Categoria
> feat: Añadir formulario y Controller de eliminacion para la entidad Categoria

- src/main/java/cl/td/g2/eventos/controller/views/FormCategoriaController.java
- src/main/resources/templates/category/list.html
feat: Añadir formulario y Controller de visualizacion para la entidad 'Categoria'
> feat: Añadir formulario y Controller de visualizacion para la entidad 'Categoria'

- src/main/resources/templates/category/list.html
fix: renombrar la url del boton nueva categoria
> fix: renombrar la url del boton nueva categoria

- src/main/resources/templates/category/edit.html
fix: homologar colores botones advertencia
> fix: homologar colores botones advertencia

- src/main/resources/templates/category/list.html
fix: homologar textop en botones advertencia
> fix: homologar textop en botones advertencia

- src/main/java/cl/td/g2/eventos/controller/views/FormCategoriaController.java
fix: limpiar method Listar Entidad Categoria
> fix: limpiar method Listar Entidad Categoria

- src/main/resources/templates/category/edit.html
(fix: optimizacion de mensajeria, parametros, y estilos para Editar Categoria)
> fix: optimizacion de mensajeria, parametros, y estilos para Editar Categoria

- src/main/resources/templates/category/form.html
fix: optimizacion de mensajeria y estilos para Guardar Categoria
> fix: optimizacion de mensajeria y estilos para Guardar Categoria

- src/main/resources/templates/layout/home.html
fix: homologar url Gestion de Categorias
> fix: homologar url Gestion de Categorias

- src/main/java/cl/td/g2/eventos/controller/views/FormCiudadController.java
fix: redireccionamiento al Crear Entidad Ciudad Backend
> fix: redireccionamiento al Crear Entidad Ciudad Backend

- src/main/resources/templates/city/form.html
fix: redireccionamiento al Crear Entidad Ciudad FrontEnd
> fix: redireccionamiento al Crear Entidad Ciudad FrontEnd

- src/main/resources/templates/layout/home.html
fix: homologar redireccionamiento url Gestion de Ciudad
> fix: homologar redireccionamiento url Gestion de Ciudad

- src/main/java/cl/td/g2/eventos/exception/GlobalExceptionHandler.java
- src/main/resources/application.properties
- src/main/resources/templates/error.html
feat: Mejorar el GlobalExceptionHandler para gestionar varias excepciones y mejorar las respuestas  de error para API y vistas
> feat: Mejorar el GlobalExceptionHandler para gestionar varias excepciones y mejorar las respuestas  de error para API y vistas

- pom.xml
- src/main/resources/application.properties
fix: optimizar version Swagger3
> fix: optimizar version Swagger3

- src/main/java/cl/td/g2/eventos/G2GestionEventosApplication.java
- src/main/resources/templates/category/form.html
- src/main/resources/templates/city/form.html
> fix: limpieza de codigo

- src/main/java/cl/td/g2/eventos/controller/views/FormCategoriaController.java
- src/main/resources/templates/category/list.html
fix: optimizacion de mensajeria, y parametrización al eliminar Categoria desde la vista Listar
> fix: optimizacion de mensajeria, y parametrización al eliminar Categoria desde la vista Listar

- src/main/resources/templates/category/edit.html
fix: optimizacion de mensajeria, y parametrización al eliminar Categoria desde la vista Editar
> fix: optimizacion de mensajeria, y parametrización al eliminar Categoria desde la vista Editar

- src/main/java/cl/td/g2/eventos/controller/views/FormCiudadController.java
- src/main/resources/templates/city/edit.html
fix: optimizacion de mensajeria, y parametrización al eliminar Ciudad desde la vista Editar
> fix: optimizacion de mensajeria, y parametrización al eliminar Ciudad desde la vista Editar

- src/main/resources/templates/city/edit.html
- src/main/resources/templates/city/list.html
fix: optimizacion de mensajeria, y parametrización al eliminar Ciudad desde la vista Listar
> fix: optimizacion de mensajeria, y parametrización al eliminar Ciudad desde la vista Listar

- src/main/java/cl/td/g2/eventos/controller/views/HomeController.java
- src/main/resources/templates/layout/privacy.html
- src/main/resources/templates/layout/terms.html
feat: Añadir vistas de Terminos y Privacidad
> feat: Añadir vistas de Terminos y Privacidad

- src/main/resources/templates/category/edit.html
- src/main/resources/templates/category/list.html
fix:  mejor experiencia en términos de accesibilidad
> fix:  mejor experiencia en términos de accesibilidad

- pom.xml
- src/main/java/cl/td/g2/eventos/controller/calendar/CalendarController.java
- src/main/resources/templates/calendario/view.html
fix: optimizacion Vista Calendario Eventos y su contenido
> fix: optimizacion Vista Calendario Eventos y su contenido

- src/main/java/cl/td/g2/eventos/controller/views/FormInscripcionController.java
- src/main/java/cl/td/g2/eventos/mapper/InscripcionMapper.java
- src/main/resources/templates/inscription/edit.html
- src/main/resources/templates/inscription/list.html
feat: Añadir formulario y Controller  para editar, listar, y Eliminar para la entidad Inscripcion
> feat: Añadir formulario y Controller  para editar, listar, y Eliminar para la entidad Inscripcion

- src/main/java/cl/td/g2/eventos/controller/views/FormUsuarioController.java
- src/main/resources/templates/user/edit.html
- src/main/resources/templates/user/list.html
feat: Añadir formulario y Controller para editar, listar, y Eliminar para la entidad Usuario
> feat: Añadir formulario y Controller para editar, listar, y Eliminar para la entidad Usuario

- src/main/java/cl/td/g2/eventos/service/EventoService.java
fix: optimizacion de inyeccion por Constructor en el EventoService
> fix: optimizacion de inyeccion por Constructor en el EventoService

- src/main/resources/templates/layout/home.html
fix: homologar redireccionamiento url Gestion de Inscripciones y Usuarios
> fix: homologar redireccionamiento url Gestion de Inscripciones y Usuarios

- src/main/resources/templates/city/edit.html
- src/main/resources/templates/city/list.html
- src/main/resources/templates/user/list.html
feat: homologacion iconos botones guardado, editado y eliminar
> feat: homologacion iconos botones guardado, editado y eliminar

- src/main/java/cl/td/g2/eventos/controller/views/HomeController.java
- src/main/resources/templates/layout/contact.html
feat: Implementacion vista Contact
> feat: Implementacion vista Contact

- src/main/java/cl/td/g2/eventos/controller/views/FormEventoController.java
feat: optimizacion de la búsqueda de la categoría y ciudad asociadas al evento
> feat: optimizacion de la búsqueda de la categoría y ciudad asociadas al evento

- src/main/resources/templates/calendario/view.html
- src/main/resources/templates/category/edit.html
- src/main/resources/templates/category/form.html
- src/main/resources/templates/category/list.html
- src/main/resources/templates/city/edit.html
- src/main/resources/templates/city/form.html
- src/main/resources/templates/city/list.html
- src/main/resources/templates/event/edit.html
- src/main/resources/templates/event/form.html
- src/main/resources/templates/event/list.html
- src/main/resources/templates/inscription/edit.html
- src/main/resources/templates/inscription/form.html
- src/main/resources/templates/inscription/list.html
- src/main/resources/templates/layout/about.html
- src/main/resources/templates/layout/contact.html
- src/main/resources/templates/layout/home.html
- src/main/resources/templates/layout/privacy.html
- src/main/resources/templates/layout/terms.html
- src/main/resources/templates/user/edit.html
- src/main/resources/templates/user/form.html
- src/main/resources/templates/user/list.html
feat: homologacion y optimizacion de todas las vistas del aplicativo. Añadir funcionalidad Google Maps
> feat: homologacion y optimizacion de todas las vistas del aplicativo. Añadir funcionalidad Google Maps

- src/main/resources/templates/event/form.html
fix: optimizacion visualizacion select formulario Al Crear Entidad Evento
> fix: optimizacion visualizacion select formulario Al Crear Entidad Evento

- fluentd/Dockerfile
- fluentd/fluent.conf
- src/main/resources/application.properties
- src/main/resources/logback-spring.xml
> configuracion basica fluentd

- pom.xml
incluir dependencias fluentd (log) y plugin sonarqube
> incluir dependencias fluentd (log) y plugin sonarqube

- src/main/java/cl/td/g2/eventos/controller/views/FormCategoriaController.java
- src/main/java/cl/td/g2/eventos/dto/CategoriaDTO.java
mejora logs para el contenedor
> mejora logs para el contenedor

- README.md
feat: update readme con la implementacion de sonar en el contenedor
> feat: update readme con la implementacion de sonar en el contenedor

- k8s/app-deployment.yaml
- k8s/docker-compose.yml
- k8s/postgres-deployment.yaml
- k8s/postgres-pv.yaml
feat: intento de implementacion de k8s
> feat: intento de implementacion de k8s
